### ISSUE TITLE
Warlock SIM - Chest reforge crit > hit imported as mastery > hit

### ISSUE THREAD

**Issue by Andengbr** [wowsims/exporter#16]
Using v2.11.2 WowSimsExporter:
![image](https://github.com/wowsims/cata/assets/119415659/b7da935f-b84f-42c3-8eee-44b405c9243b)

Character in-game stats:
![image](https://github.com/wowsims/cata/assets/119415659/cf2d6eda-1df9-4f3a-bac0-8a3f9cc3dbc9)

Chest reforge crit > hit:
![image](https://github.com/wowsims/cata/assets/119415659/b606d5f6-a2bf-4efd-84e3-97ac8415026d)

Generated import data:
`{"talents":"000000000000000000-3312222300310212211-3320200000000000000","glyphs":{"minor":[{"spellID":58094},{"spellID":56238},{"spellID":58070}],"prime":[{"spellID":56218},{"spellID":56228},{"spellID":63303}],"major":[{"spellID":63312},{"spellID":56240},{"spellID":63320}]},"class":"warlock","unit":"player","race":"Orc","name":"Aenima","gear":{"items":[{"id":65093,"gems":[68780,52217],"reforging":115,"enchant":4207},{"id":62416,"gems":[],"reforging":144},{"id":63463,"gems":[52205],"enchant":4200},{"id":59457,"gems":[],"reforging":144,"enchant":4115},{"id":67133,"gems":[52205,52217],"reforging":165,"enchant":4063},{"id":63484,"gems":[],"reforging":145,"enchant":4089},{"id":62364,"gems":[52217],"reforging":165,"enchant":4061},{"id":54503,"gems":[52217,52207],"reforging":138},{"id":60250,"gems":[52208,52207],"reforging":154,"enchant":4113},{"id":65069,"gems":[52207],"reforging":165,"enchant":4092},{"id":56380,"gems":[],"reforging":145},{"id":56276,"gems":[],"reforging":167},{"id":62465,"gems":[]},{"id":62047,"gems":[],"reforging":165},{"id":61329,"gems":[],"reforging":144,"enchant":4083},{"id":62234,"gems":[],"enchant":4091},{"id":56296,"gems":[],"reforging":167}]},"professions":[{"name":"Engineering","level":525},{"name":"Tailoring","level":525}],"level":85,"spec":"demonology","realm":"Gehennas"}`

Change in stats after import to sim:
![image](https://github.com/wowsims/cata/assets/119415659/33a3ac5e-ec81-4e1e-a5c2-10080ddc7d94)

Chest reforge in the sim showing mastery > hit
![image](https://github.com/wowsims/cata/assets/119415659/a0b761e1-5900-4067-b567-237efe75d0a3)

Changing this reforge to crit > hit corrects the stats discrepancy:
![image](https://github.com/wowsims/cata/assets/119415659/b06ae371-983f-4769-a385-a15b6244a95e)

![image](https://github.com/wowsims/cata/assets/119415659/59595f8e-3864-4a77-b83c-c0a509792175)

**Comment by MR-Valdez** [comment]
Got an issue here on my boots export as well, In Game is Haste>Crit, import is Haste>Mastery

`{"talents":"0003000000000000000000-230330221120121213231-0300000000000000000","glyphs":{"minor":["Glyph of Conjuring","Glyph of Arcane Brilliance","Glyph of Slow Fall"],"major":["Glyph of Dragon's Breath","Glyph of Evocation","Glyph of Blink"],"prime":["Glyph of Fireball","Glyph of Pyroblast","Glyph of Molten Armor"]},"class":"mage","race":"Worgen","name":"Curnil","gear":{"items":[{"enchant":4207,"gems":[68780,59493,59478],"id":59449},{"id":62434,"gems":[],"reforging":165},{"enchant":4200,"gems":[52217],"reforging":144,"id":56399},{"enchant":4115,"gems":[],"reforging":151,"id":62357},{"enchant":4063,"gems":[52207,52217],"reforging":151,"id":60244},{"enchant":4065,"gems":[],"id":56389},{"enchant":4068,"gems":[52217],"reforging":166,"id":62364},{"id":54503,"gems":[52207,52207],"reforging":166},{"enchant":4113,"gems":[52239,52207],"reforging":152,"id":60245},{"enchant":4094,"gems":[52207],"reforging":154,"id":62450},{"id":64904,"gems":[],"reforging":166},{"id":62352,"gems":[],"reforging":151},{"id":62047,"gems":[],"reforging":167},{"id":62470,"gems":[]},{"enchant":4083,"gems":[],"id":56271},null,{"id":56296,"gems":[],"reforging":166}]},"professions":[{"name":"Engineering","level":525},{"name":"Tailoring","level":525}],"level":85,"spec":"","realm":"Benediction"}`

**Comment by Tharre** [comment]
@MR-Valdez we are not the ones managing the WeakAura, try maybe the wago page or something

Though it's likely that they just copy&paste the addon code

**Comment by MR-Valdez** [comment]
@Tharre Looks like the exporter is doing it also.

Export Data:
{"talents":"0003000000000000000000-230330221120121213231-0300000000000000000","glyphs":{"minor":[{"spellID":57928},{"spellID":57924},{"spellID":57925}],"prime":[{"spellID":56368},{"spellID":56384},{"spellID":56382}],"major":[{"spellID":56373},{"spellID":56380},{"spellID":56365}]},"class":"mage","unit":"player","race":"Worgen","name":"Curnil","gear":{"items":[{"id":59449,"gems":[68780,59493,59478],"enchant":4207},{"id":62434,"gems":[],"reforging":165},{"id":56399,"gems":[52217],"reforging":151,"enchant":4200},{"id":62357,"gems":[],"reforging":151,"enchant":4115},{"id":60244,"gems":[52207,52217],"reforging":151,"enchant":4063},{"id":56389,"gems":[],"enchant":4065},{"id":62364,"gems":[52217],"reforging":165,"enchant":4068},{"id":54503,"gems":[52207,52207],"reforging":166},{"id":60245,"gems":[52239,52207],"reforging":152,"enchant":4113},{"id":62450,"gems":[52207],"reforging":154,"enchant":4094},{"id":64904,"gems":[],"reforging":165},{"id":56432,"gems":[],"reforging":138},{"id":62047,"gems":[],"reforging":166},{"id":62470,"gems":[],"reforging":137},{"id":56271,"gems":[],"reforging":152,"enchant":4083},null,{"id":56296,"gems":[],"reforging":166}]},"professions":[{"name":"Engineering","level":525},{"name":"Tailoring","level":525}],"level":85,"spec":"fire","realm":"Benediction"}

InGame Screenshot:
![InGame](https://github.com/wowsims/exporter/assets/5170242/e205c357-2c20-42f9-b729-271ade5282d0)

WowSims Screenshot:
![WowSims](https://github.com/wowsims/exporter/assets/5170242/cea9e373-d732-4269-b78f-af6b44cc3783)
